type: ipaas
info:
  name: Google Drive
  slug: google-drive

authentication:
  auth_method: "oauth2"
  oauth2:
    redirect_url: "https://api.integration.app/oauth-callback"

capabilities:
  - authorize